---
abstract: 'Kosoku WebService API'
author:
  - 'sue7ga <sue77ga@gmail.com>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Kosoku-API
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  WWW::Kosoku::API:
    file: lib/WWW/Kosoku/API.pm
    version: 0.05
requires:
  WWW::Kosoku::API: 0.03
  perl: 5.008005
resources:
  bugtracker: https://github.com/sue7ga/WWW-Kosoku-API/issues
  homepage: https://github.com/sue7ga/WWW-Kosoku-API
  repository: git://github.com/sue7ga/WWW-Kosoku-API.git
version: 0.05
